### ISSUE TITLE
some functions are not working on some glsl versions

### ISSUE THREAD

**Issue by mfiano** [cbaggers/glsl-spec#6]
It seems that some functions like ABS are not working because they have multiple entries:

https://github.com/cbaggers/glsl-spec/blob/master/functions.lisp#L8-L10

For example, ABS is not working on GLSL versions less than 410 because the last entry starts at 410. I'm not sure if this is a bug but the docs suggest I can use ABS on 330, but not with varjo.

**Comment by cbaggers** [comment]
`abs` is fixed but 'some functions' is just noise. Have you seen other functions with this issue? if so why wouldnt they be in this report. If you havent are you guessing or is this a test?

I will have another look at the functions list but I'm closing this as part that that has information is fixed and the rest is unhelpful

**Comment by cbaggers** [comment]
A quick hunt revealed these: https://github.com/cbaggers/glsl-spec/issues/8
